Admin2/Admin2/Admin2/Controllers/SportZoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Admin2.Data;
using Microsoft.AspNetCore.Mvc;
using Admin2.Data;
using Admin2.Models;
using Microsoft.EntityFrameworkCore;

namespace Admin2.Controllers
{
    public class SportZoomController : Controller
    {
        private Admin2Context context;
        public SportZoomController(Admin2Context ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            return View(context.SportRooms);
        }
        
        // GET: SubjectController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SportZoomController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Address,Hotline")] SportRoom sportRoom)
        {
            if (ModelState.IsValid)
            {
                context.Add(sportRoom);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sportRoom);
        }

        // GET: SubjectController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sportRoom = await context.SportRooms.FindAsync(id);
            if (sportRoom == null)
            {
                return NotFound();
            }
            return View(sportRoom);
        }

        // POST: SubjectController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Address,Hotline")] SportRoom sportRoom)
        {
            if (id != sportRoom.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(sportRoom);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpotZoomExists(sportRoom.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sportRoom);
        }

        // GET: SubjectController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sportRoom = await context.SportRooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (sportRoom == null)
            {
                return NotFound();
            }

            return View(sportRoom);
        }

        // POST: SubjectController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sportZoom = await context.SportRooms.FindAsync(id);
            context.SportRooms.Remove(sportZoom);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpotZoomExists(int id)
        {
            return context.SportRooms.Any(e => e.ID == id);
        }
    }
}

Admin2/Admin2/Admin2/Views/SportZoom/Create.cshtml
@model Admin2.Models.SportRoom


<section id="main-content">
    <section class="wrapper">
        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Edit Sport Zoom
                </div>
                <div>
                    <div class="row">
                        <div class="col-md-4">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="Name" class="control-label"></label>
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Address" class="control-label"></label>
                                    <input asp-for="Address" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label asp-for="Hotline" class="control-label"></label>
                                    <input asp-for="Hotline" class="form-control" />
                                    <span asp-validation-for="Hotline" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Admin2/Admin2/Admin2/Views/SportZoom/Edit.cshtml
@model Admin2.Models.SportRoom

<section id="main-content">
    <section class="wrapper">
        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Edit Sport Zoom
                </div>
                <div>
                    <div class="row">
                        <div class="col-md-4">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="ID" />
                                <div class="form-group">
                                    <label asp-for="Name" class="control-label"></label>
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Address" class="control-label"></label>
                                    <input asp-for="Address" class="form-control" />
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Hotline" class="control-label"></label>
                                    <input asp-for="Hotline" class="form-control" />
                                    <span asp-validation-for="Hotline" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Save" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Admin2/Admin2/Admin2/Views/SportZoom/Index.cshtml
@model IQueryable<SportRoom>
    
    <section id="main-content">
        <section class="wrapper">
            <div class="table-agile-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Sport Zoom
                    </div>
                    <div>
                        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
                            <thead>
                                <tr>
                                    <th data-breakpoints="xs">Name</th>
                                    <th>Address</th>
                                    <th>Hotline</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var p in Model)
                                {
                                <tr>
                                    <td>@p.Name</td>
                                    <td>@p.Address</td>
                                    <td>@p.Hotline</td>
                                    <td><a asp-action="Edit" asp-controller="SportZoom" asp-route-id="@p.ID">Edit</a></td>
                                    <td><a asp-action="DeleteConform" asp-controller="SportZoom" asp-route-id="@p.ID">Delete</a></td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>












        <script src="js/bootstrap.js"></script>
        <script src="js/jquery.dcjqaccordion.2.7.js"></script>
        <script src="js/scripts.js"></script>
        <script src="js/jquery.nicescroll.js"></script>