RYAN-sport/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RYAN_sport.Controllers
{
    public class AlbumController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RYAN-sport/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RYAN_sport.Models;
using RYAN_sport.Models.ViewModels;
using RYAN_sport.Areas.Identity.Data;
using RYAN_sport.Data;

namespace RYAN_sport.Controllers
{
    public class ContactController : Controller
    {
        private RYAN_sportDBContext context;

        public ContactController(RYAN_sportDBContext repo)
        {
            context = repo;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public IActionResult Create(string FirstName, string LastName, string Email, string PhoneNumber, string Address01, string Address02, string Messenger)
        {
            Contact contact = new Contact {FirstName = FirstName, LastName = LastName, Email = Email, PhoneNumber = PhoneNumber, Address01 = Address01, Address02 = Address02, Messenger = Messenger};
            context.Add(contact);
            context.SaveChanges();
            String StatusMessage = "Your Feedback Sent";
            return RedirectToAction(nameof(Index));
        }

    }
}

RYAN-sport/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RYAN_sport.Models;
using RYAN_sport.Models.ViewModels;
using RYAN_sport.Areas.Identity.Data;


namespace RYAN_sport.Controllers
{
    public class SubjectController : Controller
    {
        private IStoreRepository repository;
        public int PageSize = 6;

        public SubjectController(IStoreRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(string category, int productPage = 1)
             => View(new SubjectListViewModel
             {
                 Subjects = repository.Subjects
                 .Where(p => category == null || p.Category == category)
                 .OrderBy(p => p.ID)
                 .Skip((productPage - 1) * PageSize)
                 .Take(PageSize),
                 PagingInfo = new PagingInfo
                 {
                     CurrentPage = productPage,
                     ItemsPerPage = PageSize,
                     TotalItems = category == null ? repository.Subjects.Count() : repository.Subjects.Where(e => e.Category == category).Count()
                 },
                 CurrentCategory = category
             });

        public ViewResult DetailSubject(int SubjectId)
            => View(new SubjectListViewModel
            {
                Subjects = repository.Subjects
                 .Where(p => p.ID == SubjectId),
                
            });
    }
}

RYAN-sport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RYAN_sport</title>
    <link rel="stylesheet"
          href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/home.css" />
</head>
<body>
   
    <header style="top:0">
        <div class="container">
            <div class="row">
                <div class="main-header">
                    <a href="~/" class="logo">RYAN-Sport</a>
                    <div class="header-right">
                        <a href="~/">Home</a>
                        <a asp-action="Index" asp-controller="Subject">Subject</a>`
                        <a asp-action="Index" asp-controller="Contact">Contact</a>
                        <a asp-action="Index" asp-controller="Album">Album</a>
                        <partial name="_LoginPartial" />


                    </div>
                </div>
            </div>   
        </div>
    </header>
    <div style="margin-top: 100px">
        @RenderBody() 
    </div>
            
     
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>