RYAN-sport/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RYAN_sport.Models
{
    public class Subject
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "decimal(8,2)")]
        public decimal Price { get; set; }
        public string Time { get; set; }
        public string Category { get; set; }
        public string ImgSubject { get; set; }
        public string ImgSubjectDetail { get; set; }

        public virtual ICollection<LevelSubject> LevelSubjects { get; set; }
        //public virtual ICollection<Galery> Galeries { get; set; }
        public virtual ICollection<SubjectSportRoom> SubjectSportRooms { get; set; }
    }
}

RYAN-sport/Models/Subjects.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;

namespace RYAN_sport.Models
{
    public class Subjects
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "decimal(8,2)")]
        public decimal Price { get; set; }
        public string Time { get; set; }

        public virtual ICollection<Level> Levels { get; set; }
    }
}

RYAN-sport/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using RYAN_sport.Areas.Identity.Data;

namespace RYAN_sport.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepository repository;
        public NavigationMenuViewComponent(IStoreRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Subjects
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

RYAN-sport/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RYAN_sport.Models;
using RYAN_sport.Models.ViewModels;
using RYAN_sport.Areas.Identity.Data;


namespace RYAN_sport.Controllers
{
    public class SubjectController : Controller
    {
        private IStoreRepository repository;
        public int PageSize = 6;

        public SubjectController(IStoreRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(string category, int productPage = 1)
             => View(new SubjectListViewModel
             {
                 Subjects = repository.Subjects
                 .Where(p => category == null || p.Category == category)
                 .OrderBy(p => p.ID)
                 .Skip((productPage - 1) * PageSize)
                 .Take(PageSize),
                 PagingInfo = new PagingInfo
                 {
                     CurrentPage = productPage,
                     ItemsPerPage = PageSize,
                     TotalItems = category == null ? repository.Subjects.Count() : repository.Subjects.Where(e => e.Category == category).Count()
                 },
                 CurrentCategory = category
             });

        public ViewResult DetailSubject(int SubjectId)
            => View(new SubjectListViewModel
            {
                Subjects = repository.Subjects
                 .Where(p => p.ID == SubjectId),
                
            });
    }
}

RYAN-sport/Views/Subject/DetailSubject.cshtml
@model SubjectListViewModel
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v9.0" nonce="cLpVju4t"></script>
<style>
    * {
        box-sizing: border-box
    }

    body {
        font-family: Verdana, sans-serif;
        margin: 0;
        padding: 0;
    }

    header {
        background-color: rgb(48, 54, 60);
        /*position: fixed;*/
        /*z-index: 10;*/
        /*margin-left: 8.2%;*/
        /*border-radius: 40px;*/
        /*width: 85%;*/
        /*padding-left: 40px;*/
        /*padding-right: 40px;*/
        /*margin-top: 7px;*/
        /*transition: .4s;*/
    }

    .main-header {
        float: left;
        padding: 20px 0px 20px 0px;
    }

    .header-right {
        float: right;
    }

    header a {
        padding-right: 15px;
        font-size: 14px;
        margin: 0;
        font-weight: 700;
        line-height: 50px;
        color: #FFF;
        text-transform: uppercase;
        text-decoration: none;
        padding-top: 50px;
    }

    header .logo {
        font-size: 25px;
    }

    header a:hover {
        color: #0da1ff;
        transition: 0.5s;
    }

    .main-header a span {
        position: absolute;
        top: 23px;
        right: 309px;
        width: 17px;
        height: 17px;
        text-align: center;
        font-size: 12px;
        display: inline-block;
        line-height: 18px;
        border-radius: 2px;
    }

    header.sticky {
        margin: 0px;
        width: 100%;
        border-radius: 0px;
        height: 92px;
        background: #30363cf5;
    }

    .section2 {
        background-image: url("https://1bubze2sol6cfove63681xma-wpengine.netdna-ssl.com/wp-content/uploads/2015/12/bread-crumb-bg.jpg");
        background-repeat: repeat;
        background-position: right;
        width: 100%;
        float: left;
        margin-bottom: 50px;
        clear: both;
        background-color: rgb(235, 235, 235);
    }

    .banner-activities {
        display: inline-block;
        width: 100%;
        padding: 20px 0px 5px;
        margin-top: 0px;
        float: left;
    }

        .banner-activities h2 {
            color: #0DA1FF;
        }

    .breadcrumb {
        float: right;
        background: none;
    }

        .breadcrumb a {
            text-decoration: none;
            color: #0d6efd;
        }

            .breadcrumb a:hover {
                color: gray;
                transition: 0.5s;
            }

        .breadcrumb h4 {
            font-weight: 100;
            padding-top: 2px;
            font-size: 18px;
            /*color: #212529;*/
        }

        .breadcrumb span {
            color: #212529;
        }

    .list-menu ul li {
        padding-bottom: 20px;
        border-bottom: 1px solid #ebebeb;
        padding-top: 20px;
    }

    .list-menu ul {
        list-style: none;
        padding: 0;
        /*border-bottom: 1px solid #4d4d4d;*/
    }

        .list-menu ul li a {
            text-decoration: none;
            padding: 10px 10px 10px 40px;
            color: black;
            font-weight: 600;
        }

    .list-menu a:hover {
        color: #FFFFFF;
        transition: 1s;
    }

    .list-menu ul li:hover {
        transition: 1s;
        background-color: #0da1ff;
        /*border: 1px solid #0da1ff;*/
        color: #FFFFFF;
    }

    .content-sec3 h2 {
        font-weight: 700;
        text-transform: uppercase;
        font-size: 25px;
        padding-top: 20px;
    }

    .content-sec3 p {
        padding-top: 30px;
    }

    .activities_schedule {
        margin-top: 25px;
        margin-bottom: 30px;
        float: left;
        background-color: #0da1ff;
        text-align: center;
        color: #FFFFFF;
    }

        .activities_schedule i {
            margin-top: 35px;
            margin-bottom: 15px;
            border: 2px solid #FFFFFF;
            padding: 15px 15px 15px 15px;
            font-size: 26px;
        }

        .activities_schedule h5 {
            text-transform: uppercase;
            font-size: 14px;
            font-weight: 700;
        }

        .activities_schedule p {
            /*padding-top: 15px;*/
            padding: 10px 15px 30px 15px;
            font-size: 14px;
            letter-spacing: -1px;
        }

    .pricing-title {
        padding: 25px 15px 25px 15px;
        background-color: #0da1ff;
        color: #FFFFFF;
    }

        .pricing-title h3 {
            text-transform: uppercase;
            margin-bottom: 8px;
            color: #FFF;
            font-size: 18px;
            font-weight: 700;
        }

        .pricing-title span {
            font-size: 14px;
        }

    .pricing-price1 {
        float: left;
        background-color: #f6f6f6;
    }

    .pricing-price2 {
        background-color: #efefef;
        float: right;
    }

    .pricing-price p {
        font-size: 25px;
        font-weight: 600;
    }

    .pricing-price span {
        padding-bottom: 50px;
    }

    header {
        margin: 0px;
        width: 100%;
        border-radius: 0px;
        height: 92px;
        background: #30363cf5;
    }
</style>
<section class="section2">
    <div class="container">
        <div class="row">
            <div class="banner-activities">
                <h2 style="float: left">Subject Details</h2>
                <div class="breadcrumb" style="padding-top: 12px;">
                    <a href="~/">Home</a>&gt
                    <a href="~/Subject">Subject</a>&gt
                    <span class="default">
                        <h4>Subject Details</h4>
                    </span>
                </div>
            </div>

        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            @foreach (var t in Model.Subjects)
            {
                <img style="margin-top:-47px" src="@t.ImgSubjectDetail" />
            }

        </div>
    </div>
</section>

<section class="section3">
    <div class="container">
        <div class="row">
            <div class="col-xl-12" style="padding-top: 35px">
                <div class="list-menu col-xl-4" style="float: left">
                    <ul>
                        <li><a href="~/DetailSubject/Id=1">BASEKETBALL</a></li>
                        <li><a href="~/DetailSubject/Id=2">BADMINTON</a></li>
                        <li><a href="~/DetailSubject/Id=4">FOOTBAll</a></li>
                        <li><a href="~/DetailSubject/Id=5">WEIGHT TRAINING</a></li>
                        <li><a href="~/DetailSubject/Id=6">TRACKS TRAINING</a></li>
                        <li><a href="~/DetailSubject/Id=7">TENNIS</a></li>
                        <li><a href="~/DetailSubject/Id=8">SWIMMING</a></li>
                        <li><a href="~/DetailSubject/Id=9">GOLF</a></li>
                        <li><a href="~/DetailSubject/Id=10">CYCING</a></li>
                    </ul>
                </div>
                @foreach (var p in Model.Subjects)
                {
                    <div class="content-sec3 col-xl-8" style="float: right;padding-left: 50px;">
                        <h2>@p.Name</h2>
                        <p>@p.Description</p>

                        <h2>Activities schedule</h2>

                        <div class="activities_schedule col-xl-4">
                            <i class='fas fa-hands-helping'></i>
                            <h5>Choose your sport</h5>
                            <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything.</p>
                        </div>
                        <div class="activities_schedule col-xl-4" style="background-color: #0d88d6">
                            <i class='fas fa-book-reader'></i>
                            <h5>Train professionally</h5>
                            <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything.</p>
                        </div>
                        <div class="activities_schedule col-xl-4" style="background-color: #0B7CC4">
                            <i class='fas fa-star'></i>
                            <h5>Become a Pro</h5>
                            <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything.</p>
                        </div>

                    </div>
                }

                <div class="fb-comments" data-href="https://toan0868985852.github.io/TodoApp-reactjs/" data-numposts="5" data-width="" style="margin-left:32vw; margin-bottom: 80px"></div>

            </div>
        </div>
    </div>
</section>

<footer>
    <div class="container">
        <div class="row">
            <div class="column1 col-xl-3" style="width: 22%">
                <h3 style="text-transform: uppercase">Ryan</h3>
                <p style="font-size: 14px; line-height: 2">
                    The point of using Lorem Ipsum is that it has a more-or-less
                    normal distribution of letters, as opposed to using 'Content here,
                    making it look like readable English.
                </p>
                <p class="icon-footer">
                    <a href="#">
                        <i style="width: 15px" class="fab fa-facebook-f"></i>
                    </a>
                    <a href="#">
                        <i style="width: 15px" class="fab fa-google-plus-g"></i>
                    </a>
                    <a href="#"><i style="width: 15px" class="fab fa-twitter"></i></a>
                    <a href="#"><i style="width: 15px" class="fab fa-youtube"></i></a>
                </p>

                <p></p>
            </div>

            <div class="column1 col-xl-3" style="width: 22%">
                <h3 style="text-transform: uppercase">Useful links</h3>
                <ul>
                    <li><a href="#">Membership Offers</a></li>
                    <li>
                        <a style="border-top: solid 1px #f4f4f4" href="#">Training Schedule</a>
                    </li>
                    <li>
                        <a style="border-top: solid 1px #f4f4f4" href="#">Inter Competitions</a>
                    </li>
                    <li>
                        <a style="border-top: solid 1px #f4f4f4" href="#">Awards & Trophies</a>
                    </li>
                </ul>
            </div>
            <div class="column1 col-xl-3" style="width: 22%">
                <h3 style="text-transform: uppercase" ;>Latest posts</h3>
                <img src="~/imgLogin/basketball-team-70x60.jpg" />
                <div style="float: right; margin-top: -10px; margin-right: 5px">
                    <h4><a href="#">Basketball Team</a></h4>
                    <p style="font-size: 13px; margin-top: -26px; padding-left: 16px">
                        11 Feb 2015
                    </p>
                </div>
                <div>
                    <img src="~/imgLogin/golf-70x60.jpg" style="padding-top: 15px" />
                    <div style="float: right; margin-top: 10px; padding-right: 20px">
                        <h4><a href="#">Tee Shot Zone</a></h4>
                        <p style="font-size: 13px; margin-top: -26px; padding-left: 16px">
                            11 Feb 2015
                        </p>
                    </div>
                </div>
            </div>
            <div class="column1 col-xl-3" style="width: 22%; float: right">
                <h3 style="text-transform: uppercase">About ryan</h3>
                <ul style="list-style: none; padding: 0">
                    <li>Monday - Friday<span>04:00 - 12:00</span></li>
                    <li style="
                  border-top: 1px solid #f4f4f4;
                  border-bottom: 1px solid #f4f4f4;
                ">
                        Saturday<span>14:00 - 21:00</span>
                    </li>
                    <li>Sunday<span>Holiday</span></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

RYAN-sport/Views/Subject/Index.cshtml
@model SubjectListViewModel
<div class="sb-price">
    <div id="categories" style="height: 100px;display: flex;justify-content: center;align-items: center;">
        <vc:navigation-menu />
    </div>
    <div class="container">
        <div class="row">
            <div class="details col-xl-12" style="flex-wrap: wrap;">
                <style>
                    .first-details {
                        width: 365px;
                        height: 535px;
                        margin-bottom: 45px;
                    }

                    .details-price span {
                        font-size: 20px;
                        color: #2D2D2D;
                        font-weight: 600;
                    }

                    .details {
                        display: flex;
                        justify-content: space-around;
                    }

                    .first-content a {
                        text-decoration: none;
                        border: 1px solid gray;
                        background: gray;
                        color: white;
                        padding: 10px 126px;
                        margin-left: 0px;
                        position: relative;
                        top: 30px;
                    }

                    .btn-group > .btn-group:not(:last-child) > .btn, .btn-group > .btn:not(:last-child):not(.dropdown-toggle) {
                        margin-left: 40vw;
                        margin-right: 20px;
                    }
                </style>
                @foreach (var p in Model.Subjects)
                {
                    <div class="first-details col-xl-4" style="margin-top: 20px; padding-top: 10px ">
                        <img style="width: 100%; height: 291px" src="@p.ImgSubject" />
                        <div class="first-content">
                            <h3>@p.Name</h3>
                            <span>Training Center</span>
                            <p style="padding-top: 0px;padding-top: 0px; height: 30px; width: 100%;overflow: hidden;text-overflow: ellipsis;">
                                @p.Description
                            </p>
                            <div class="details-price">
                                <span>$&nbsp;@p.Price</span> -
                                <i class='far fa-clock'>&nbsp;@p.Time &nbsp;Days</i>
                            </div>
                            <a class="regiter" href="DetailSubject/Id=@p.ID" style="padding: 10px 112px">Register</a>
                        </div>
                    </div>
                }


            </div>

            <div page-model="@Model.PagingInfo" page-action="Index"
                 page-classes-enabled="true"
                 page-class="btn" page-class-normal="btn-outline-dark"
                 page-class-selected="btn-primary"
                 page-url-category="@Model.CurrentCategory"
                 class="btn-group pull-right m-1" style="width:100px"></div>
        </div>
    </div>
</div>

<footer>
    <div class="container">
        <div class="row">
            <div class="column1 col-xl-3" style="width: 22%">
                <h3 style="text-transform: uppercase">Ryan</h3>
                <p style="font-size: 14px; line-height: 2">
                    The point of using Lorem Ipsum is that it has a more-or-less
                    normal distribution of letters, as opposed to using 'Content here,
                    making it look like readable English.
                </p>
                <p class="icon-footer">
                    <a href="#">
                        <i style="width: 15px" class="fab fa-facebook-f"></i>
                    </a>
                    <a href="#">
                        <i style="width: 15px" class="fab fa-google-plus-g"></i>
                    </a>
                    <a href="#"><i style="width: 15px" class="fab fa-twitter"></i></a>
                    <a href="#"><i style="width: 15px" class="fab fa-youtube"></i></a>
                </p>

                <p></p>
            </div>

            <div class="column1 col-xl-3" style="width: 22%">
                <h3 style="text-transform: uppercase">Useful links</h3>
                <ul>
                    <li><a href="#">Membership Offers</a></li>
                    <li>
                        <a style="border-top: solid 1px #f4f4f4" href="#">Training Schedule</a>
                    </li>
                    <li>
                        <a style="border-top: solid 1px #f4f4f4" href="#">Inter Competitions</a>
                    </li>
                    <li>
                        <a style="border-top: solid 1px #f4f4f4" href="#">Awards & Trophies</a>
                    </li>
                </ul>
            </div>
            <div class="column1 col-xl-3" style="width: 22%">
                <h3 style="text-transform: uppercase" ;>Latest posts</h3>
                <img src="~/imgLogin/basketball-team-70x60.jpg" />
                <div style="float: right; margin-top: -10px; margin-right: 5px">
                    <h4><a href="#">Basketball Team</a></h4>
                    <p style="font-size: 13px; margin-top: -26px; padding-left: 16px">
                        11 Feb 2015
                    </p>
                </div>
                <div>
                    <img src="~/imgLogin/golf-70x60.jpg" style="padding-top: 15px" />
                    <div style="float: right; margin-top: 10px; padding-right: 20px">
                        <h4><a href="#">Tee Shot Zone</a></h4>
                        <p style="font-size: 13px; margin-top: -26px; padding-left: 16px">
                            11 Feb 2015
                        </p>
                    </div>
                </div>
            </div>
            <div class="column1 col-xl-3" style="width: 22%; float: right">
                <h3 style="text-transform: uppercase">About ryan</h3>
                <ul style="list-style: none; padding: 0">
                    <li>Monday - Friday<span>04:00 - 12:00</span></li>
                    <li style="
                  border-top: 1px solid #f4f4f4;
                  border-bottom: 1px solid #f4f4f4;
                ">
                        Saturday<span>14:00 - 21:00</span>
                    </li>
                    <li>Sunday<span>Holiday</span></li>
                </ul>
            </div>
        </div>
    </div>
</footer>